import "./globals.css";

export const metadata = {
  title: "Lucinei Verneque",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <head></head>
      <body>
        {children}
      </body>
    </html>
  );
}
