'use client';

import "./globals.css";
import { useState } from "react";

const metadata = {
  title: "Lucinei Verneque",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <html lang="en" className={darkMode ? 'dark' : ''}>
      <head></head>
      <body>
        <button onClick={() => setDarkMode(!darkMode)}>
          {darkMode ? 'Modo Claro' : 'Modo Escuro'}
        </button>
        {children}
      </body>
    </html>
  );
}
